version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: db-store
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
    ports:
      - 5432:5432
volumes:
  pgdata:
    name: pgdata-store
